# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RecipeSearch' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Moya'
pod 'Moya-ObjectMapper'
pod 'ObjectMapper'
pod 'moa'
pod 'ReachabilitySwift'
pod 'SwiftPullToRefresh'
pod 'RealmSwift'
pod 'SwiftMessages'

end
